

spring:
  application:
    name: bookstore-cloud-bookservice

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://BSS1:9001/eureka/,http://BSS2:9002/eureka/
server:
  port: 8010
